Ext.define('Personal.model.Integrante', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'apenom', type: 'string' },
        { name: 'anio', type: 'string' },
		{name:'personal_id', type: 'int'},
		{name:'cedula', type: 'string'},
		{name:'sexo', type: 'string'},
		{name:'estado_civil', type: 'string'},
		{name:'direccion', type: 'string'},
		{name:'zonapos', type: 'string'},
		{name:'telefonos', type: 'string'},
		{name:'email', type: 'string'},
		{name:'fecnac', type: 'date', dateFormat: 'Y-m-d'},
		{name:'lugarnac', type: 'string'},
		{name:'codpro', type: 'string'},
		{name:'foto', type: 'string'},
		{name:'tipnom', type: 'int'},
		{name:'codnivel1', type: 'int'},
		{name:'codnivel2', type: 'int'},
		{name:'codnivel3', type: 'int'},
		{name:'codnivel4', type: 'int'},
		{name:'codnivel5', type: 'int'},
		{name:'ficha', type: 'int'},
		{name:'fecing', type: 'date', dateFormat: 'Y-m-d'},
		{name:'codcat', type: 'int'},
		{name:'codcargo', type: 'int'},
		{name:'nomposicion_id', type: 'int'},
		{name:'forcob', type: 'string'},
		{name:'codbancob', type: 'int'},
		{name:'cuentacob', type: 'string'},
		{name:'codbanlph', type: 'int'},
		{name:'cuentalph', type: 'string'},
		{name:'estado', type: 'string'},
		{name:'estado_des', type: 'string'},
		{name:'tipemp', type: 'string'},
		{name:'fecfin', type: 'int'},
		{name:'sueldopro', type: 'float'},
		{name:'fechaplica', type: 'date', dateFormat: 'Y-m-d'},
		{name:'codidi', type: 'int'},
		{name:'fecnacr', type: 'string'},
		{name:'tipopres', type: 'int'},
		{name:'fechasus', type: 'date', dateFormat: 'Y-m-d'},
		{name:'fechareisus', type: 'date', dateFormat: 'Y-m-d'},
		{name:'fechavac', type: 'date', dateFormat: 'Y-m-d'},
		{name:'fechareivac', type: 'date', dateFormat: 'Y-m-d'},
		{name:'fecharetiro', type: 'date', dateFormat: 'Y-m-d'},
		{name:'aplicalogro', type: 'int'},
		{name:'aplicasuspension', type: 'int'},
		{name:'ctacontab', type: 'string'},
		{name:'periodo', type: 'int'},
		{name:'markar', type: 'int'},
		{name:'cod_tli', type: 'string'},
		{name:'motivo_liq', type: 'string'},
		{name:'preaviso', type: 'string'},
		{name:'suesal', type: 'float'},
		{name:'contrato', type: 'string'},
		{name:'nombres', type: 'string'},
		{name:'apellidos', type: 'string'},
		{name:'montoliq', type: 'float'},
		{name:'sfecnac', type: 'string'},
		{name:'sfecing', type: 'date', dateFormat: 'Y-m-d'},
		{name:'sfecfin', type: 'string'},
		{name:'sfechaplica', type: 'string'},
		{name:'sfechasus', type: 'string'},
		{name:'sfechareisus', type: 'string'},
		{name:'sfechavac', type: 'string'},
		{name:'sfechareivac', type: 'string'},
		{name:'sfecharetiro', type: 'string'},
		{name:'nacionalidad', type: 'int'},
		{name:'diascontrato', type: 'int'},
		{name:'ee', type: 'int'},
		{name:'dfecnac', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfecing', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfecfin', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfechaplica', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfechasus', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfechareisus', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfechavac', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfechareivac', type: 'date', dateFormat: 'Y-m-d'},
		{name:'dfecharetiro', type: 'date', dateFormat: 'Y-m-d'},
		{name:'nrocuadrilla', type: 'string'},
		{name:'codnivel6', type: 'string'},
		{name:'codnivel7', type: 'string'},
		{name:'inicio_periodo', type: 'date', dateFormat: 'Y-m-d'},
		{name:'fin_periodo', type: 'date', dateFormat: 'Y-m-d'},
		{name:'fechajubipensi', type: 'date', dateFormat: 'Y-m-d'},
		{name:'porjubipensi', type: 'string'},
		{name:'antiguedadap', type: 'string'},
		{name:'paso', type: 'int'},
		{name:'motivo_retiro', type: 'string'},
		{name:'turno_id', type: 'int'},
		{name:'seguro_social', type: 'string'},
		{name:'segurosocial_sipe', type: 'string'},
		{name:'hora_base', type: 'float'},
		{name:'dv', type: 'string'},
		{name:'num_decreto', type: 'string'},
		{name:'fecha_decreto', type: 'date', dateFormat: 'Y-m-d'},
		{name:'num_decreto_baja', type: 'string'},
		{name:'fecha_decreto_baja', type: 'date', dateFormat: 'Y-m-d'},
		{name:'siacap', type: 'string'},
		{name:'puesto_id', type: 'int'},
		{name:'imagen_cedula', type: 'string'},
	]
});